interface cardIf{
    id:number;
    type:string;
    classCard:number;
    value:number;
    backCard:string;
    img:string;
}
export const card:cardIf[] = [
    {
        id:1,
        type:'bich',
        classCard:1,
        value:1,
        backCard:'../../../cards/back.png',
        img:'../../../cards/AS.png'
    },
    {
        id:2,
        type:'bich',
        classCard:1,
        value:2,
        backCard:'../../../cards/back.png',
        img:'../../../cards/2S.png'
    },
    {
        id:3,
        type:'bich',
        classCard:1,
        value:3,
        backCard:'../../../cards/back.png',
        img:'../../../cards/3S.png'
    },
    {
        id:4,
        type:'bich',
        classCard:1,
        value:4,
        backCard:'../../../cards/back.png',
        img:'../../../cards/4S.png'
    },
    {
        id:5,
        type:'bich',
        classCard:1,
        value:5,
        backCard:'../../../cards/back.png',
        img:'../../../cards/5S.png'
    },
    {
        id:6,
        type:'bich',
        classCard:1,
        value:6,
        backCard:'../../../cards/back.png',
        img:'../../../cards/6S.png'
    },
    {
        id:7,
        type:'bich',
        classCard:1,
        value:7,
        backCard:'../../../cards/back.png',
        img:'../../../cards/7S.png'
    },
    {
        id:8,
        type:'bich',
        classCard:1,
        value:8,
        backCard:'../../../cards/back.png',
        img:'../../../cards/8S.png'
    },
    {
        id:9,
        type:'bich',
        classCard:1,
        value:9,
        backCard:'../../../cards/back.png',
        img:'../../../cards/9S.png'
    },
    {
        id:10,
        type:'bich',
        classCard:1,
        value:10,
        backCard:'../../../cards/back.png',
        img:'../../../cards/10S.png'
    },
    {
        id:11,
        type:'bich',
        classCard:1,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/JS2.png'
    },
    {
        id:12,
        type:'bich',
        classCard:1,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/QS2.png'
    },
    {
        id:13,
        type:'bich',
        classCard:1,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/KS2.png'
    },
    {
        id:14,
        type:'nhep',
        classCard:2,
        value:1,
        backCard:'../../../cards/back.png',
        img:'../../../cards/AC.png'
    },
    {
        id:15,
        type:'nhep',
        classCard:2,
        value:2,
        backCard:'../../../cards/back.png',
        img:'../../../cards/2C.png'
    },
    {
        id:16,
        type:'nhep',
        classCard:2,
        value:3,
        backCard:'../../../cards/back.png',
        img:'../../../cards/3C.png'
    },
    {
        id:17,
        type:'nhep',
        classCard:2,
        value:4,
        backCard:'../../../cards/back.png',
        img:'../../../cards/4C.png'
    },
    {
        id:18,
        type:'nhep',
        classCard:2,
        value:5,
        backCard:'../../../cards/back.png',
        img:'../../../cards/5C.png'
    },
    {
        id:19,
        type:'nhep',
        classCard:2,
        value:6,
        backCard:'../../../cards/back.png',
        img:'../../../cards/6C.png'
    },
    {
        id:20,
        type:'nhep',
        classCard:2,
        value:7,
        backCard:'../../../cards/back.png',
        img:'../../../cards/7C.png'
    },
    {
        id:21,
        type:'nhep',
        classCard:2,
        value:8,
        backCard:'../../../cards/back.png',
        img:'../../../cards/8C.png'
    },
    {
        id:22,
        type:'nhep',
        classCard:2,
        value:9,
        backCard:'../../../cards/back.png',
        img:'../../../cards/9C.png'
    },
    {
        id:23,
        type:'nhep',
        classCard:2,
        value:10,
        backCard:'../../../cards/back.png',
        img:'../../../cards/10C.png'
    },
    {
        id:24,
        type:'nhep',
        classCard:2,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/JC2.png'
    },
    {
        id:25,
        type:'nhep',
        classCard:2,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/QC2.png'
    },
    {
        id:26,
        type:'nhep',
        classCard:2,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/KC2.png'
    },
    {
        id:27,
        type:'ro',
        classCard:3,
        value:1,
        backCard:'../../../cards/back.png',
        img:'../../../cards/AD.png'
    },
    {
        id:28,
        type:'ro',
        classCard:3,
        value:2,
        backCard:'../../../cards/back.png',
        img:'../../../cards/2D.png'
    },
    {
        id:29,
        type:'ro',
        classCard:3,
        value:3,
        backCard:'../../../cards/back.png',
        img:'../../../cards/3D.png'
    },
    {
        id:30,
        type:'ro',
        classCard:3,
        value:4,
        backCard:'../../../cards/back.png',
        img:'../../../cards/4D.png'
    },
    {
        id:31,
        type:'ro',
        classCard:3,
        value:5,
        backCard:'../../../cards/back.png',
        img:'../../../cards/5D.png'
    },
    {
        id:32,
        type:'ro',
        classCard:3,
        value:6,
        backCard:'../../../cards/back.png',
        img:'../../../cards/6D.png'
    },
    {
        id:33,
        type:'ro',
        classCard:3,
        value:7,
        backCard:'../../../cards/back.png',
        img:'../../../cards/7D.png'
    },
    {
        id:34,
        type:'ro',
        classCard:3,
        value:8,
        backCard:'../../../cards/back.png',
        img:'../../../cards/8D.png'
    },
    {
        id:35,
        type:'ro',
        classCard:3,
        value:9,
        backCard:'../../../cards/back.png',
        img:'../../../cards/9D.png'
    },
    {
        id:36,
        type:'ro',
        classCard:3,
        value:10,
        backCard:'../../../cards/back.png',
        img:'../../../cards/10D.png'
    },
    {
        id:37,
        type:'ro',
        classCard:3,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/JD2.png'
    },
    {
        id:38,
        type:'ro',
        classCard:3,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/QD2.png'
    },
    {
        id:39,
        type:'ro',
        classCard:3,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/KD2.png'
    },
    {
        id:40,
        type:'co',
        classCard:4,
        value:1,
        backCard:'../../../cards/back.png',
        img:'../../../cards/AH.png'
    },
    {
        id:41,
        type:'co',
        classCard:4,
        value:2,
        backCard:'../../../cards/back.png',
        img:'../../../cards/2H.png'
    },
    {
        id:42,
        type:'co',
        classCard:4,
        value:3,
        backCard:'../../../cards/back.png',
        img:'../../../cards/3H.png'
    },
    {
        id:43,
        type:'co',
        classCard:4,
        value:4,
        backCard:'../../../cards/back.png',
        img:'../../../cards/4H.png'
    },
    {
        id:44,
        type:'co',
        classCard:4,
        value:5,
        backCard:'../../../cards/back.png',
        img:'../../../cards/5H.png'
    },
    {
        id:45,
        type:'co',
        classCard:4,
        value:6,
        backCard:'../../../cards/back.png',
        img:'../../../cards/6H.png'
    },
    {
        id:46,
        type:'co',
        classCard:4,
        value:7,
        backCard:'../../../cards/back.png',
        img:'../../../cards/7H.png'
    },
    {
        id:47,
        type:'co',
        classCard:4,
        value:8,
        backCard:'../../../cards/back.png',
        img:'../../../cards/8H.png'
    },
    {
        id:48,
        type:'co',
        classCard:4,
        value:9,
        backCard:'../../../cards/back.png',
        img:'../../../cards/9H.png'
    },
    {
        id:49,
        type:'co',
        classCard:4,
        value:10,
        backCard:'../../../cards/back.png',
        img:'../../../cards/10H.png'
    },
    {
        id:50,
        type:'co',
        classCard:4,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/JH2.png'
    },
    {
        id:51,
        type:'co',
        classCard:4,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/QH2.png'
    },
    {
        id:52,
        type:'co',
        classCard:4,
        value:0,
        backCard:'../../../cards/back.png',
        img:'../../../cards/KH2.png'
    },
]